# Generated by Django 4.1.1 on 2022-09-22 00:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('nascimento', models.DateField(default=uuid.uuid4, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=15, null=True)),
                ('endereco', models.CharField(max_length=50)),
                ('data_admissão', models.DateField(default=uuid.uuid4, unique=True)),
                ('contrato', models.CharField(default=uuid.uuid4, max_length=20, unique=True)),
                ('função', models.CharField(max_length=15)),
                ('salario', models.DecimalField(decimal_places=3, max_digits=5)),
                ('setor', models.CharField(choices=[('DP', 'Departamento Pessoal'), ('TI', 'Departamento de TI'), ('RH', 'Recursos Humanos'), ('AMOX', 'Almoxarifado')], max_length=12)),
            ],
        ),
    ]
