# Generated by Django 4.1.1 on 2022-09-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_model',
            old_name='cpf',
            new_name='CPF',
        ),
        migrations.AlterField(
            model_name='register_model',
            name='contrato',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='register_model',
            name='data_admissão',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='register_model',
            name='função',
            field=models.CharField(choices=[('DEV', 'Developer JR'), ('DEV', 'Developer PLENO'), ('DEV', 'Developer SENIOR'), ('TEC_LEAD', 'Tech Lead'), ('Analista', 'Analista de RH'), ('Gerente', 'Gerente')], max_length=15),
        ),
        migrations.AlterField(
            model_name='register_model',
            name='nascimento',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='register_model',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
